export const passages: Record<string, string> = {
  heatIsland: `The phenomenon of "urban heat islands" arises when densely built environments absorb and retain solar radiation far more efficiently than surrounding rural areas. Dark impervious surfaces—roads, rooftops, parking lots—replace vegetation that would otherwise release moisture through evapotranspiration, a cooling mechanism. As a result, city centers can register temperatures 1–7°C higher than nearby countryside, intensifying energy demand for cooling, worsening air quality, and exacerbating heat-related illness among vulnerable populations.`,
  scienceRev: `Historians of science have long debated whether scientific revolutions follow a gradual accumulation of evidence or occur in sudden paradigm shifts, as Thomas Kuhn famously argued. Recent cognitive science research complicates both models: it suggests that scientists, like all humans, exhibit confirmation bias—a tendency to seek data confirming existing beliefs—which slows incremental change. Yet it also shows that when anomalies accumulate beyond a threshold, belief revision can be remarkably rapid. This implies that progress is neither purely gradualist nor purely revolutionary but oscillates between periods of biased stability and sudden reorganization.`,
  coralReef: `Coral reefs occupy less than one percent of the ocean floor yet support roughly a quarter of all marine species. Their structural complexity provides habitat niches unavailable elsewhere. Rising sea temperatures trigger mass bleaching events in which corals expel symbiotic algae, losing both color and primary energy source. While some reefs recover if stress abates quickly, repeated bleaching within short intervals can convert diverse ecosystems into algae-dominated flats. Conservation efforts now emphasize reducing local stressors—overfishing, pollution—to buy time while global emissions decline.`,
  memoryResearch: `Psychologists distinguish between episodic memory, which records personal experiences, and semantic memory, which stores general facts detached from context. Neuroimaging studies suggest these systems rely on overlapping but not identical neural networks. Patients with hippocampal damage often retain factual knowledge while struggling to recall when or where they learned it. This dissociation challenges earlier models that treated memory as a single faculty and has influenced educational design, encouraging spaced retrieval practice over passive review.`,
  tradePolicy: `Proponents of free trade argue that removing tariffs allows countries to specialize according to comparative advantage, lowering prices and expanding consumer choice. Critics counter that unfettered trade can hollow out domestic manufacturing, concentrate environmental harm in nations with weak regulation, and increase vulnerability to supply-chain shocks. Empirical evidence supports elements of both views: aggregate gains coexist with localized losses that policy rarely compensates fully. Modern trade agreements therefore increasingly embed labor and environmental standards, attempting to reconcile efficiency with distributional fairness.`,
  RenaissanceArt: `Renaissance patrons did not merely commission art for aesthetic pleasure; they used visual propaganda to assert political legitimacy. Portraits emphasized lineage, virtue, and divine favor through symbolic objects—globes, books, laurel wreaths—readable to literate elites. The shift toward naturalistic perspective reflected both technical innovation and humanist philosophy, yet artists remained dependent on patron tastes that could abruptly change with regime turnover. Understanding Renaissance art thus requires reading images as arguments embedded in specific power structures rather than as timeless expressions of beauty.`,
  biodiversity: `Island ecosystems often exhibit high endemism because geographic isolation limits gene flow and allows unique adaptations to flourish. Introduced predators or competitors can devastate native populations lacking evolutionary defenses against them. New Zealand's flightless birds, for example, declined sharply after mammalian predators arrived with human settlers. Restoration projects now combine predator exclusion fences, captive breeding, and gradual reintroduction, but success depends on sustained funding and community support long after initial publicity fades.`,
  linguistics: `Languages change continuously, yet speakers perceive their own dialect as stable. Sound shifts spread through social networks rather than uniformly across regions, producing gradual divergence that can eventually hinder mutual intelligibility. Written standards often lag behind spoken innovation, creating tension in education between prescriptive grammar and descriptive accuracy. Linguists argue that no dialect is inherently deficient; judgments of correctness reflect social prestige rather than logical superiority, a insight with implications for classroom equity and assessment design.`,
  economicsBehavior: `Classical economic models assume rational agents maximizing utility with complete information. Behavioral economists document systematic deviations: loss aversion makes people weigh potential losses more heavily than equivalent gains; present bias leads to under-saving for retirement despite long-term intentions. These findings do not invalidate market mechanisms but suggest policy tools—default enrollment in pension plans, simplified disclosure formats—that preserve choice while steering behavior toward stated goals. The debate continues over how aggressively governments should employ such "nudges."`,
  archaeology: `Archaeological interpretation rarely proceeds from artifacts to single definitive narratives. A pottery shard might indicate trade routes, dietary shifts, or ritual practice depending on contextual association. Radiocarbon dating revolutionized chronology but requires calibration and careful sample selection to avoid contamination. Indigenous communities increasingly demand collaborative stewardship of excavated materials, challenging museums built on colonial acquisition practices. Contemporary archaeology therefore blends scientific method with ethical negotiation, acknowledging that the past is reconstructed through present values as well as empirical evidence.`,
};
