import { Question } from "../../types";

export const readingComprehensionQuestions: Question[] = [
{
  id: `v1`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `The phenomenon of "urban heat islands" arises when densely built environments absorb and retain solar radiation far more efficiently than surrounding rural areas. Dark impervious surfaces—roads, rooftops, parking lots—replace vegetation that would otherwise release moisture through evapotranspiration, a cooling mechanism. As a result, city centers can register temperatures 1–7°C higher than nearby countryside, intensifying energy demand for cooling, worsening air quality, and exacerbating heat-related illness among vulnerable populations.`,
  prompt: `According to the passage, which of the following best explains why urban areas are hotter than rural areas?`,
  options: [`Urban residents consume more energy than rural residents.`, `Impervious surfaces replace vegetation that would otherwise cool through moisture release.`, `Cities generate more greenhouse gases per capita than rural regions.`, `Rural areas benefit from stronger prevailing winds that dissipate heat.`, `Urban buildings trap cold air, creating a contrast effect.`],
  correctAnswer: `Impervious surfaces replace vegetation that would otherwise cool through moisture release.`,
  explanation: `The passage states that roads and rooftops replace vegetation that releases moisture via evapotranspiration—a cooling mechanism—directly causing the temperature differential.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `heatIsland`],
},

{
  id: `v2`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `The phenomenon of "urban heat islands" arises when densely built environments absorb and retain solar radiation far more efficiently than surrounding rural areas. Dark impervious surfaces—roads, rooftops, parking lots—replace vegetation that would otherwise release moisture through evapotranspiration, a cooling mechanism. As a result, city centers can register temperatures 1–7°C higher than nearby countryside, intensifying energy demand for cooling, worsening air quality, and exacerbating heat-related illness among vulnerable populations.`,
  prompt: `The author mentions "vulnerable populations" primarily to:`,
  options: [`Provide a statistical demographic breakdown of city dwellers.`, `Suggest that urban heat primarily affects outdoor workers.`, `Illustrate one of the human costs of the urban heat island effect.`, `Argue that rural populations are relatively safe from heat-related illness.`, `Emphasize that only the elderly are at risk from rising temperatures.`],
  correctAnswer: `Illustrate one of the human costs of the urban heat island effect.`,
  explanation: `The reference caps a list of negative consequences, functioning as an illustration of human cost rather than a demographic claim.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `heatIsland`],
},

{
  id: `v3`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Historians of science have long debated whether scientific revolutions follow a gradual accumulation of evidence or occur in sudden paradigm shifts, as Thomas Kuhn famously argued. Recent cognitive science research complicates both models: it suggests that scientists, like all humans, exhibit confirmation bias—a tendency to seek data confirming existing beliefs—which slows incremental change. Yet it also shows that when anomalies accumulate beyond a threshold, belief revision can be remarkably rapid. This implies that progress is neither purely gradualist nor purely revolutionary but oscillates between periods of biased stability and sudden reorganization.`,
  prompt: `Which of the following, if true, would most weaken the passage's conclusion?`,
  options: [`Thomas Kuhn's model has been criticized by historians who prefer gradualist accounts.`, `Confirmation bias is equally present in non-scientific communities.`, `Studies show that scientists consistently revise beliefs smoothly rather than in sudden bursts, even when anomalies are numerous.`, `The threshold at which anomalies trigger rapid belief revision varies across disciplines.`, `Cognitive scientists have replicated confirmation bias findings in multiple cultural contexts.`],
  correctAnswer: `Studies show that scientists consistently revise beliefs smoothly rather than in sudden bursts, even when anomalies are numerous.`,
  explanation: `The conclusion posits oscillation between stability and sudden reorganization. Evidence of only smooth revision removes the sudden component.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `scienceRev`],
},

{
  id: `v4`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Historians of science have long debated whether scientific revolutions follow a gradual accumulation of evidence or occur in sudden paradigm shifts, as Thomas Kuhn famously argued. Recent cognitive science research complicates both models: it suggests that scientists, like all humans, exhibit confirmation bias—a tendency to seek data confirming existing beliefs—which slows incremental change. Yet it also shows that when anomalies accumulate beyond a threshold, belief revision can be remarkably rapid. This implies that progress is neither purely gradualist nor purely revolutionary but oscillates between periods of biased stability and sudden reorganization.`,
  prompt: `The passage suggests that confirmation bias in science primarily:`,
  options: [`Prevents any scientific progress from occurring.`, `Slows incremental change while not eliminating the possibility of rapid revision.`, `Ensures that paradigm shifts occur more frequently than Kuhn predicted.`, `Affects only junior researchers rather than established scientists.`, `Is stronger in experimental fields than in theoretical ones.`],
  correctAnswer: `Slows incremental change while not eliminating the possibility of rapid revision.`,
  explanation: `The passage states confirmation bias slows incremental change yet anomalies can still trigger rapid belief revision beyond a threshold.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `scienceRev`],
},

{
  id: `v5`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Coral reefs occupy less than one percent of the ocean floor yet support roughly a quarter of all marine species. Their structural complexity provides habitat niches unavailable elsewhere. Rising sea temperatures trigger mass bleaching events in which corals expel symbiotic algae, losing both color and primary energy source. While some reefs recover if stress abates quickly, repeated bleaching within short intervals can convert diverse ecosystems into algae-dominated flats. Conservation efforts now emphasize reducing local stressors—overfishing, pollution—to buy time while global emissions decline.`,
  prompt: `The passage implies that reducing local stressors on reefs:`,
  options: [`Eliminates the need for global emissions reductions.`, `Can improve resilience while broader climate action proceeds.`, `Is ineffective if sea temperatures continue rising.`, `Primarily benefits shallow-water species.`, `Has been rejected by most conservation organizations.`],
  correctAnswer: `Can improve resilience while broader climate action proceeds.`,
  explanation: `The passage says local stressor reduction can 'buy time while global emissions decline,' implying complementary—not substitute—actions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `coralReef`],
},

{
  id: `v6`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Coral reefs occupy less than one percent of the ocean floor yet support roughly a quarter of all marine species. Their structural complexity provides habitat niches unavailable elsewhere. Rising sea temperatures trigger mass bleaching events in which corals expel symbiotic algae, losing both color and primary energy source. While some reefs recover if stress abates quickly, repeated bleaching within short intervals can convert diverse ecosystems into algae-dominated flats. Conservation efforts now emphasize reducing local stressors—overfishing, pollution—to buy time while global emissions decline.`,
  prompt: `According to the passage, repeated bleaching events within short intervals may:`,
  options: [`Increase coral biodiversity through adaptive evolution.`, `Convert diverse reefs into algae-dominated ecosystems.`, `Strengthen symbiotic algae populations permanently.`, `Have no lasting effect if water quality improves.`, `Reduce the total area occupied by coral globally to zero.`],
  correctAnswer: `Convert diverse reefs into algae-dominated ecosystems.`,
  explanation: `The passage explicitly states repeated bleaching can convert diverse ecosystems into algae-dominated flats.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `coralReef`],
},

{
  id: `v7`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Psychologists distinguish between episodic memory, which records personal experiences, and semantic memory, which stores general facts detached from context. Neuroimaging studies suggest these systems rely on overlapping but not identical neural networks. Patients with hippocampal damage often retain factual knowledge while struggling to recall when or where they learned it. This dissociation challenges earlier models that treated memory as a single faculty and has influenced educational design, encouraging spaced retrieval practice over passive review.`,
  prompt: `Patients with hippocampal damage, as described in the passage, would most likely:`,
  options: [`Forget all factual knowledge acquired before injury.`, `Recall personal experiences more vividly than facts.`, `Retain general facts while struggling to place learning in time or context.`, `Improve at spaced retrieval practice.`, `Show identical deficits in episodic and semantic memory.`],
  correctAnswer: `Retain general facts while struggling to place learning in time or context.`,
  explanation: `The passage notes such patients often retain factual knowledge while struggling to recall when or where they learned it.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `memoryResearch`],
},

{
  id: `v8`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Proponents of free trade argue that removing tariffs allows countries to specialize according to comparative advantage, lowering prices and expanding consumer choice. Critics counter that unfettered trade can hollow out domestic manufacturing, concentrate environmental harm in nations with weak regulation, and increase vulnerability to supply-chain shocks. Empirical evidence supports elements of both views: aggregate gains coexist with localized losses that policy rarely compensates fully. Modern trade agreements therefore increasingly embed labor and environmental standards, attempting to reconcile efficiency with distributional fairness.`,
  prompt: `The passage characterizes modern trade agreements as attempting to:`,
  options: [`Eliminate all tariffs worldwide within a fixed timeline.`, `Replace comparative advantage theory with protectionism.`, `Balance efficiency gains with labor and environmental standards.`, `Compensate every worker displaced by import competition.`, `Prioritize supply-chain resilience over consumer prices exclusively.`],
  correctAnswer: `Balance efficiency gains with labor and environmental standards.`,
  explanation: `The passage states agreements increasingly embed labor and environmental standards to reconcile efficiency with distributional fairness.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `tradePolicy`],
},

{
  id: `v9`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Renaissance patrons did not merely commission art for aesthetic pleasure; they used visual propaganda to assert political legitimacy. Portraits emphasized lineage, virtue, and divine favor through symbolic objects—globes, books, laurel wreaths—readable to literate elites. The shift toward naturalistic perspective reflected both technical innovation and humanist philosophy, yet artists remained dependent on patron tastes that could abruptly change with regime turnover. Understanding Renaissance art thus requires reading images as arguments embedded in specific power structures rather than as timeless expressions of beauty.`,
  prompt: `According to the passage, Renaissance portraits often included symbolic objects in order to:`,
  options: [`Demonstrate the artist's technical mastery of still life.`, `Convey political messages readable to educated viewers.`, `Satisfy religious requirements for iconographic accuracy.`, `Reduce the cost of commissioning large canvases.`, `Document daily material culture for future historians.`],
  correctAnswer: `Convey political messages readable to educated viewers.`,
  explanation: `The passage states patrons used visual propaganda through symbolic objects readable to literate elites to assert legitimacy.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `RenaissanceArt`],
},

{
  id: `v10`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Island ecosystems often exhibit high endemism because geographic isolation limits gene flow and allows unique adaptations to flourish. Introduced predators or competitors can devastate native populations lacking evolutionary defenses against them. New Zealand's flightless birds, for example, declined sharply after mammalian predators arrived with human settlers. Restoration projects now combine predator exclusion fences, captive breeding, and gradual reintroduction, but success depends on sustained funding and community support long after initial publicity fades.`,
  prompt: `The New Zealand example in the passage primarily illustrates:`,
  options: [`How captive breeding always fails for flightless birds.`, `The vulnerability of isolated species to introduced predators.`, `That endemism is unrelated to geographic isolation.`, `The superiority of mammalian predators in island ecosystems.`, `Why restoration projects avoid community involvement.`],
  correctAnswer: `The vulnerability of isolated species to introduced predators.`,
  explanation: `Flightless birds declined after mammalian predators arrived—showing isolated species lack defenses against new threats.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `biodiversity`],
},

{
  id: `v11`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Languages change continuously, yet speakers perceive their own dialect as stable. Sound shifts spread through social networks rather than uniformly across regions, producing gradual divergence that can eventually hinder mutual intelligibility. Written standards often lag behind spoken innovation, creating tension in education between prescriptive grammar and descriptive accuracy. Linguists argue that no dialect is inherently deficient; judgments of correctness reflect social prestige rather than logical superiority, a insight with implications for classroom equity and assessment design.`,
  prompt: `The passage suggests that judgments about grammatical correctness often reflect:`,
  options: [`Logical superiority of standard written forms.`, `Universal cognitive constraints on language acquisition.`, `Social prestige rather than inherent linguistic deficiency.`, `The speed of sound shifts across social networks.`, `Agreement between prescriptive and descriptive linguistics.`],
  correctAnswer: `Social prestige rather than inherent linguistic deficiency.`,
  explanation: `Linguists argue no dialect is inherently deficient; correctness judgments reflect social prestige.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `linguistics`],
},

{
  id: `v12`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Classical economic models assume rational agents maximizing utility with complete information. Behavioral economists document systematic deviations: loss aversion makes people weigh potential losses more heavily than equivalent gains; present bias leads to under-saving for retirement despite long-term intentions. These findings do not invalidate market mechanisms but suggest policy tools—default enrollment in pension plans, simplified disclosure formats—that preserve choice while steering behavior toward stated goals. The debate continues over how aggressively governments should employ such "nudges."`,
  prompt: `Behavioral economists, according to the passage, would most likely support:`,
  options: [`Eliminating all consumer choice in financial markets.`, `Default pension enrollment to address present bias.`, `Rejecting empirical evidence from classical models entirely.`, `Banning loss aversion through regulation.`, `Assuming agents always maximize utility with complete information.`],
  correctAnswer: `Default pension enrollment to address present bias.`,
  explanation: `The passage cites default enrollment as a policy tool steering behavior toward stated goals despite present bias.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `economicsBehavior`],
},

{
  id: `v13`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Archaeological interpretation rarely proceeds from artifacts to single definitive narratives. A pottery shard might indicate trade routes, dietary shifts, or ritual practice depending on contextual association. Radiocarbon dating revolutionized chronology but requires calibration and careful sample selection to avoid contamination. Indigenous communities increasingly demand collaborative stewardship of excavated materials, challenging museums built on colonial acquisition practices. Contemporary archaeology therefore blends scientific method with ethical negotiation, acknowledging that the past is reconstructed through present values as well as empirical evidence.`,
  prompt: `The passage indicates that contemporary archaeology:`,
  options: [`Relies solely on radiocarbon dating for all interpretations.`, `Treats artifacts as yielding single definitive narratives.`, `Integrates scientific methods with ethical collaboration.`, `Rejects indigenous claims to excavated materials.`, `Avoids contextual association when analyzing pottery.`],
  correctAnswer: `Integrates scientific methods with ethical collaboration.`,
  explanation: `The passage describes blending scientific method with ethical negotiation and collaborative stewardship.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `archaeology`],
},

{
  id: `v14`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Coral reefs occupy less than one percent of the ocean floor yet support roughly a quarter of all marine species. Their structural complexity provides habitat niches unavailable elsewhere. Rising sea temperatures trigger mass bleaching events in which corals expel symbiotic algae, losing both color and primary energy source. While some reefs recover if stress abates quickly, repeated bleaching within short intervals can convert diverse ecosystems into algae-dominated flats. Conservation efforts now emphasize reducing local stressors—overfishing, pollution—to buy time while global emissions decline.`,
  prompt: `The author's tone toward current conservation efforts is best described as:`,
  options: [`Dismissive`, `Cautiously pragmatic`, `Triumphalist`, `Indifferent`, `Sarcastic`],
  correctAnswer: `Cautiously pragmatic`,
  explanation: `Conservation is portrayed as necessary but insufficient alone—pragmatically buying time rather than guaranteeing success.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `coralReef`],
},

{
  id: `v15`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Psychologists distinguish between episodic memory, which records personal experiences, and semantic memory, which stores general facts detached from context. Neuroimaging studies suggest these systems rely on overlapping but not identical neural networks. Patients with hippocampal damage often retain factual knowledge while struggling to recall when or where they learned it. This dissociation challenges earlier models that treated memory as a single faculty and has influenced educational design, encouraging spaced retrieval practice over passive review.`,
  prompt: `Spaced retrieval practice is mentioned to show how research on memory has:`,
  options: [`Invalidated all classroom testing.`, `Influenced practical educational design.`, `Proven episodic memory unimportant.`, `Ended debate between memory systems.`, `Replaced neuroimaging methods.`],
  correctAnswer: `Influenced practical educational design.`,
  explanation: `The passage links the episodic/semantic distinction to educational design favoring spaced retrieval.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `memoryResearch`],
},

{
  id: `v16`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Proponents of free trade argue that removing tariffs allows countries to specialize according to comparative advantage, lowering prices and expanding consumer choice. Critics counter that unfettered trade can hollow out domestic manufacturing, concentrate environmental harm in nations with weak regulation, and increase vulnerability to supply-chain shocks. Empirical evidence supports elements of both views: aggregate gains coexist with localized losses that policy rarely compensates fully. Modern trade agreements therefore increasingly embed labor and environmental standards, attempting to reconcile efficiency with distributional fairness.`,
  prompt: `Critics of free trade, as presented, would most likely emphasize:`,
  options: [`Universal consumer price reductions.`, `Localized economic and environmental harms.`, `The obsolescence of comparative advantage.`, `Elimination of supply-chain vulnerability.`, `Complete compensation for displaced workers.`],
  correctAnswer: `Localized economic and environmental harms.`,
  explanation: `Critics cite hollowing manufacturing, environmental harm abroad, and supply-chain vulnerability.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `tradePolicy`],
},

{
  id: `v17`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Island ecosystems often exhibit high endemism because geographic isolation limits gene flow and allows unique adaptations to flourish. Introduced predators or competitors can devastate native populations lacking evolutionary defenses against them. New Zealand's flightless birds, for example, declined sharply after mammalian predators arrived with human settlers. Restoration projects now combine predator exclusion fences, captive breeding, and gradual reintroduction, but success depends on sustained funding and community support long after initial publicity fades.`,
  prompt: `Which statement is most strongly supported by the passage regarding biodiversity?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `biodiversity`],
},

{
  id: `v18`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Languages change continuously, yet speakers perceive their own dialect as stable. Sound shifts spread through social networks rather than uniformly across regions, producing gradual divergence that can eventually hinder mutual intelligibility. Written standards often lag behind spoken innovation, creating tension in education between prescriptive grammar and descriptive accuracy. Linguists argue that no dialect is inherently deficient; judgments of correctness reflect social prestige rather than logical superiority, a insight with implications for classroom equity and assessment design.`,
  prompt: `Which statement is most strongly supported by the passage regarding linguistics?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `linguistics`],
},

{
  id: `v19`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Classical economic models assume rational agents maximizing utility with complete information. Behavioral economists document systematic deviations: loss aversion makes people weigh potential losses more heavily than equivalent gains; present bias leads to under-saving for retirement despite long-term intentions. These findings do not invalidate market mechanisms but suggest policy tools—default enrollment in pension plans, simplified disclosure formats—that preserve choice while steering behavior toward stated goals. The debate continues over how aggressively governments should employ such "nudges."`,
  prompt: `Which statement is most strongly supported by the passage regarding economics Behavior?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `economicsBehavior`],
},

{
  id: `v20`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Archaeological interpretation rarely proceeds from artifacts to single definitive narratives. A pottery shard might indicate trade routes, dietary shifts, or ritual practice depending on contextual association. Radiocarbon dating revolutionized chronology but requires calibration and careful sample selection to avoid contamination. Indigenous communities increasingly demand collaborative stewardship of excavated materials, challenging museums built on colonial acquisition practices. Contemporary archaeology therefore blends scientific method with ethical negotiation, acknowledging that the past is reconstructed through present values as well as empirical evidence.`,
  prompt: `Which statement is most strongly supported by the passage regarding archaeology?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `archaeology`],
},

{
  id: `v21`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `The phenomenon of "urban heat islands" arises when densely built environments absorb and retain solar radiation far more efficiently than surrounding rural areas. Dark impervious surfaces—roads, rooftops, parking lots—replace vegetation that would otherwise release moisture through evapotranspiration, a cooling mechanism. As a result, city centers can register temperatures 1–7°C higher than nearby countryside, intensifying energy demand for cooling, worsening air quality, and exacerbating heat-related illness among vulnerable populations.`,
  prompt: `Which statement is most strongly supported by the passage regarding heat Island?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `heatIsland`],
},

{
  id: `v22`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Historians of science have long debated whether scientific revolutions follow a gradual accumulation of evidence or occur in sudden paradigm shifts, as Thomas Kuhn famously argued. Recent cognitive science research complicates both models: it suggests that scientists, like all humans, exhibit confirmation bias—a tendency to seek data confirming existing beliefs—which slows incremental change. Yet it also shows that when anomalies accumulate beyond a threshold, belief revision can be remarkably rapid. This implies that progress is neither purely gradualist nor purely revolutionary but oscillates between periods of biased stability and sudden reorganization.`,
  prompt: `Which statement is most strongly supported by the passage regarding science Rev?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `scienceRev`],
},

{
  id: `v23`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Coral reefs occupy less than one percent of the ocean floor yet support roughly a quarter of all marine species. Their structural complexity provides habitat niches unavailable elsewhere. Rising sea temperatures trigger mass bleaching events in which corals expel symbiotic algae, losing both color and primary energy source. While some reefs recover if stress abates quickly, repeated bleaching within short intervals can convert diverse ecosystems into algae-dominated flats. Conservation efforts now emphasize reducing local stressors—overfishing, pollution—to buy time while global emissions decline.`,
  prompt: `Which statement is most strongly supported by the passage regarding coral Reef?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `coralReef`],
},

{
  id: `v24`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Psychologists distinguish between episodic memory, which records personal experiences, and semantic memory, which stores general facts detached from context. Neuroimaging studies suggest these systems rely on overlapping but not identical neural networks. Patients with hippocampal damage often retain factual knowledge while struggling to recall when or where they learned it. This dissociation challenges earlier models that treated memory as a single faculty and has influenced educational design, encouraging spaced retrieval practice over passive review.`,
  prompt: `Which statement is most strongly supported by the passage regarding memory Research?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `memoryResearch`],
},

{
  id: `v25`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Proponents of free trade argue that removing tariffs allows countries to specialize according to comparative advantage, lowering prices and expanding consumer choice. Critics counter that unfettered trade can hollow out domestic manufacturing, concentrate environmental harm in nations with weak regulation, and increase vulnerability to supply-chain shocks. Empirical evidence supports elements of both views: aggregate gains coexist with localized losses that policy rarely compensates fully. Modern trade agreements therefore increasingly embed labor and environmental standards, attempting to reconcile efficiency with distributional fairness.`,
  prompt: `Which statement is most strongly supported by the passage regarding trade Policy?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `tradePolicy`],
},

{
  id: `v26`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Renaissance patrons did not merely commission art for aesthetic pleasure; they used visual propaganda to assert political legitimacy. Portraits emphasized lineage, virtue, and divine favor through symbolic objects—globes, books, laurel wreaths—readable to literate elites. The shift toward naturalistic perspective reflected both technical innovation and humanist philosophy, yet artists remained dependent on patron tastes that could abruptly change with regime turnover. Understanding Renaissance art thus requires reading images as arguments embedded in specific power structures rather than as timeless expressions of beauty.`,
  prompt: `Which statement is most strongly supported by the passage regarding Renaissance Art?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `RenaissanceArt`],
},

{
  id: `v27`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Island ecosystems often exhibit high endemism because geographic isolation limits gene flow and allows unique adaptations to flourish. Introduced predators or competitors can devastate native populations lacking evolutionary defenses against them. New Zealand's flightless birds, for example, declined sharply after mammalian predators arrived with human settlers. Restoration projects now combine predator exclusion fences, captive breeding, and gradual reintroduction, but success depends on sustained funding and community support long after initial publicity fades.`,
  prompt: `Which statement is most strongly supported by the passage regarding biodiversity?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `biodiversity`],
},

{
  id: `v28`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Languages change continuously, yet speakers perceive their own dialect as stable. Sound shifts spread through social networks rather than uniformly across regions, producing gradual divergence that can eventually hinder mutual intelligibility. Written standards often lag behind spoken innovation, creating tension in education between prescriptive grammar and descriptive accuracy. Linguists argue that no dialect is inherently deficient; judgments of correctness reflect social prestige rather than logical superiority, a insight with implications for classroom equity and assessment design.`,
  prompt: `Which statement is most strongly supported by the passage regarding linguistics?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `linguistics`],
},

{
  id: `v29`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Classical economic models assume rational agents maximizing utility with complete information. Behavioral economists document systematic deviations: loss aversion makes people weigh potential losses more heavily than equivalent gains; present bias leads to under-saving for retirement despite long-term intentions. These findings do not invalidate market mechanisms but suggest policy tools—default enrollment in pension plans, simplified disclosure formats—that preserve choice while steering behavior toward stated goals. The debate continues over how aggressively governments should employ such "nudges."`,
  prompt: `Which statement is most strongly supported by the passage regarding economics Behavior?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `economicsBehavior`],
},

{
  id: `v30`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Archaeological interpretation rarely proceeds from artifacts to single definitive narratives. A pottery shard might indicate trade routes, dietary shifts, or ritual practice depending on contextual association. Radiocarbon dating revolutionized chronology but requires calibration and careful sample selection to avoid contamination. Indigenous communities increasingly demand collaborative stewardship of excavated materials, challenging museums built on colonial acquisition practices. Contemporary archaeology therefore blends scientific method with ethical negotiation, acknowledging that the past is reconstructed through present values as well as empirical evidence.`,
  prompt: `Which statement is most strongly supported by the passage regarding archaeology?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `archaeology`],
},

{
  id: `v31`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `The phenomenon of "urban heat islands" arises when densely built environments absorb and retain solar radiation far more efficiently than surrounding rural areas. Dark impervious surfaces—roads, rooftops, parking lots—replace vegetation that would otherwise release moisture through evapotranspiration, a cooling mechanism. As a result, city centers can register temperatures 1–7°C higher than nearby countryside, intensifying energy demand for cooling, worsening air quality, and exacerbating heat-related illness among vulnerable populations.`,
  prompt: `Which statement is most strongly supported by the passage regarding heat Island?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `heatIsland`],
},

{
  id: `v32`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Historians of science have long debated whether scientific revolutions follow a gradual accumulation of evidence or occur in sudden paradigm shifts, as Thomas Kuhn famously argued. Recent cognitive science research complicates both models: it suggests that scientists, like all humans, exhibit confirmation bias—a tendency to seek data confirming existing beliefs—which slows incremental change. Yet it also shows that when anomalies accumulate beyond a threshold, belief revision can be remarkably rapid. This implies that progress is neither purely gradualist nor purely revolutionary but oscillates between periods of biased stability and sudden reorganization.`,
  prompt: `Which statement is most strongly supported by the passage regarding science Rev?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `scienceRev`],
},

{
  id: `v33`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Coral reefs occupy less than one percent of the ocean floor yet support roughly a quarter of all marine species. Their structural complexity provides habitat niches unavailable elsewhere. Rising sea temperatures trigger mass bleaching events in which corals expel symbiotic algae, losing both color and primary energy source. While some reefs recover if stress abates quickly, repeated bleaching within short intervals can convert diverse ecosystems into algae-dominated flats. Conservation efforts now emphasize reducing local stressors—overfishing, pollution—to buy time while global emissions decline.`,
  prompt: `Which statement is most strongly supported by the passage regarding coral Reef?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `coralReef`],
},

{
  id: `v34`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Psychologists distinguish between episodic memory, which records personal experiences, and semantic memory, which stores general facts detached from context. Neuroimaging studies suggest these systems rely on overlapping but not identical neural networks. Patients with hippocampal damage often retain factual knowledge while struggling to recall when or where they learned it. This dissociation challenges earlier models that treated memory as a single faculty and has influenced educational design, encouraging spaced retrieval practice over passive review.`,
  prompt: `Which statement is most strongly supported by the passage regarding memory Research?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `memoryResearch`],
},

{
  id: `v35`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Proponents of free trade argue that removing tariffs allows countries to specialize according to comparative advantage, lowering prices and expanding consumer choice. Critics counter that unfettered trade can hollow out domestic manufacturing, concentrate environmental harm in nations with weak regulation, and increase vulnerability to supply-chain shocks. Empirical evidence supports elements of both views: aggregate gains coexist with localized losses that policy rarely compensates fully. Modern trade agreements therefore increasingly embed labor and environmental standards, attempting to reconcile efficiency with distributional fairness.`,
  prompt: `Which statement is most strongly supported by the passage regarding trade Policy?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `tradePolicy`],
},

{
  id: `v36`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Renaissance patrons did not merely commission art for aesthetic pleasure; they used visual propaganda to assert political legitimacy. Portraits emphasized lineage, virtue, and divine favor through symbolic objects—globes, books, laurel wreaths—readable to literate elites. The shift toward naturalistic perspective reflected both technical innovation and humanist philosophy, yet artists remained dependent on patron tastes that could abruptly change with regime turnover. Understanding Renaissance art thus requires reading images as arguments embedded in specific power structures rather than as timeless expressions of beauty.`,
  prompt: `Which statement is most strongly supported by the passage regarding Renaissance Art?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `RenaissanceArt`],
},

{
  id: `v37`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Island ecosystems often exhibit high endemism because geographic isolation limits gene flow and allows unique adaptations to flourish. Introduced predators or competitors can devastate native populations lacking evolutionary defenses against them. New Zealand's flightless birds, for example, declined sharply after mammalian predators arrived with human settlers. Restoration projects now combine predator exclusion fences, captive breeding, and gradual reintroduction, but success depends on sustained funding and community support long after initial publicity fades.`,
  prompt: `Which statement is most strongly supported by the passage regarding biodiversity?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `biodiversity`],
},

{
  id: `v38`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Languages change continuously, yet speakers perceive their own dialect as stable. Sound shifts spread through social networks rather than uniformly across regions, producing gradual divergence that can eventually hinder mutual intelligibility. Written standards often lag behind spoken innovation, creating tension in education between prescriptive grammar and descriptive accuracy. Linguists argue that no dialect is inherently deficient; judgments of correctness reflect social prestige rather than logical superiority, a insight with implications for classroom equity and assessment design.`,
  prompt: `Which statement is most strongly supported by the passage regarding linguistics?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `linguistics`],
},

{
  id: `v39`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Classical economic models assume rational agents maximizing utility with complete information. Behavioral economists document systematic deviations: loss aversion makes people weigh potential losses more heavily than equivalent gains; present bias leads to under-saving for retirement despite long-term intentions. These findings do not invalidate market mechanisms but suggest policy tools—default enrollment in pension plans, simplified disclosure formats—that preserve choice while steering behavior toward stated goals. The debate continues over how aggressively governments should employ such "nudges."`,
  prompt: `Which statement is most strongly supported by the passage regarding economics Behavior?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `economicsBehavior`],
},

{
  id: `v40`,
  section: `verbal`,
  type: `reading-comprehension`,
  passage: `Archaeological interpretation rarely proceeds from artifacts to single definitive narratives. A pottery shard might indicate trade routes, dietary shifts, or ritual practice depending on contextual association. Radiocarbon dating revolutionized chronology but requires calibration and careful sample selection to avoid contamination. Indigenous communities increasingly demand collaborative stewardship of excavated materials, challenging museums built on colonial acquisition practices. Contemporary archaeology therefore blends scientific method with ethical negotiation, acknowledging that the past is reconstructed through present values as well as empirical evidence.`,
  prompt: `Which statement is most strongly supported by the passage regarding archaeology?`,
  options: [`The passage provides a single uncontested conclusion.`, `Multiple causal factors interact in the phenomenon described.`, `The author rejects all prior scholarly models entirely.`, `Empirical evidence is absent from the discussion.`, `The topic is unrelated to contemporary policy debates.`],
  correctAnswer: `Multiple causal factors interact in the phenomenon described.`,
  explanation: `GRE passages typically present nuanced, multi-causal accounts rather than single definitive conclusions.`,
  difficulty: `medium`,
  tags: [`reading-comprehension`, `archaeology`],
}
];
