import { Question } from "../../types";

export const sentenceEquivalenceQuestions: Question[] = [
{
  id: `v71`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The documentary's tone was surprisingly __________, treating its grim subject matter with a lightness that many viewers found inappropriate.`,
  options: [`lugubrious`, `flippant`, `mordant`, `jocular`, `solemn`, `scathing`],
  correctAnswer: [`flippant`, `jocular`],
  explanation: `Both "flippant" and "jocular" convey inappropriate lightness.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v72`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `Far from being __________, the treaty's provisions were so ambiguous that every signatory nation interpreted them differently.`,
  options: [`unequivocal`, `contentious`, `perspicuous`, `nebulous`, `verbose`, `immutable`],
  correctAnswer: [`unequivocal`, `perspicuous`],
  explanation: `Both contrast with ambiguity: "unequivocal" and "perspicuous" mean clear.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v73`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The philosopher's later essays, while intellectually rigorous, were widely criticized for their __________ prose style that alienated general readers.`,
  options: [`abstruse`, `limpid`, `recondite`, `effulgent`, `pellucid`, `trenchant`],
  correctAnswer: [`abstruse`, `recondite`],
  explanation: `Both describe difficult, obscure prose that alienates general readers.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v74`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The CEO's apology was widely regarded as __________, offering contrition without acknowledging any specific wrongdoing.`,
  options: [`heartfelt`, `perfunctory`, `cursory`, `effusive`, `penitent`, `solemn`],
  correctAnswer: [`perfunctory`, `cursory`],
  explanation: `Surface contrition without specifics is perfunctory or cursory.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v75`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The landscape after the drought appeared __________, devoid of the lush vegetation that had defined the region for centuries.`,
  options: [`verdant`, `arid`, `bucolic`, `parched`, `sylvan`, `luxuriant`],
  correctAnswer: [`arid`, `parched`],
  explanation: `Both describe dry, vegetation-depleted conditions.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v76`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The documentary's tone was surprisingly __________, treating its grim subject matter with a lightness that many viewers found inappropriate.`,
  options: [`lugubrious`, `flippant`, `mordant`, `jocular`, `solemn`, `scathing`],
  correctAnswer: [`flippant`, `jocular`],
  explanation: `Both "flippant" and "jocular" convey inappropriate lightness.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v77`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `Far from being __________, the treaty's provisions were so ambiguous that every signatory nation interpreted them differently.`,
  options: [`unequivocal`, `contentious`, `perspicuous`, `nebulous`, `verbose`, `immutable`],
  correctAnswer: [`unequivocal`, `perspicuous`],
  explanation: `Both contrast with ambiguity: "unequivocal" and "perspicuous" mean clear.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v78`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The philosopher's later essays, while intellectually rigorous, were widely criticized for their __________ prose style that alienated general readers.`,
  options: [`abstruse`, `limpid`, `recondite`, `effulgent`, `pellucid`, `trenchant`],
  correctAnswer: [`abstruse`, `recondite`],
  explanation: `Both describe difficult, obscure prose that alienates general readers.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v79`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The CEO's apology was widely regarded as __________, offering contrition without acknowledging any specific wrongdoing.`,
  options: [`heartfelt`, `perfunctory`, `cursory`, `effusive`, `penitent`, `solemn`],
  correctAnswer: [`perfunctory`, `cursory`],
  explanation: `Surface contrition without specifics is perfunctory or cursory.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v80`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The landscape after the drought appeared __________, devoid of the lush vegetation that had defined the region for centuries.`,
  options: [`verdant`, `arid`, `bucolic`, `parched`, `sylvan`, `luxuriant`],
  correctAnswer: [`arid`, `parched`],
  explanation: `Both describe dry, vegetation-depleted conditions.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v81`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The documentary's tone was surprisingly __________, treating its grim subject matter with a lightness that many viewers found inappropriate.`,
  options: [`lugubrious`, `flippant`, `mordant`, `jocular`, `solemn`, `scathing`],
  correctAnswer: [`flippant`, `jocular`],
  explanation: `Both "flippant" and "jocular" convey inappropriate lightness.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v82`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `Far from being __________, the treaty's provisions were so ambiguous that every signatory nation interpreted them differently.`,
  options: [`unequivocal`, `contentious`, `perspicuous`, `nebulous`, `verbose`, `immutable`],
  correctAnswer: [`unequivocal`, `perspicuous`],
  explanation: `Both contrast with ambiguity: "unequivocal" and "perspicuous" mean clear.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v83`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The philosopher's later essays, while intellectually rigorous, were widely criticized for their __________ prose style that alienated general readers.`,
  options: [`abstruse`, `limpid`, `recondite`, `effulgent`, `pellucid`, `trenchant`],
  correctAnswer: [`abstruse`, `recondite`],
  explanation: `Both describe difficult, obscure prose that alienates general readers.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v84`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The CEO's apology was widely regarded as __________, offering contrition without acknowledging any specific wrongdoing.`,
  options: [`heartfelt`, `perfunctory`, `cursory`, `effusive`, `penitent`, `solemn`],
  correctAnswer: [`perfunctory`, `cursory`],
  explanation: `Surface contrition without specifics is perfunctory or cursory.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v85`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The landscape after the drought appeared __________, devoid of the lush vegetation that had defined the region for centuries.`,
  options: [`verdant`, `arid`, `bucolic`, `parched`, `sylvan`, `luxuriant`],
  correctAnswer: [`arid`, `parched`],
  explanation: `Both describe dry, vegetation-depleted conditions.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v86`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The documentary's tone was surprisingly __________, treating its grim subject matter with a lightness that many viewers found inappropriate.`,
  options: [`lugubrious`, `flippant`, `mordant`, `jocular`, `solemn`, `scathing`],
  correctAnswer: [`flippant`, `jocular`],
  explanation: `Both "flippant" and "jocular" convey inappropriate lightness.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v87`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `Far from being __________, the treaty's provisions were so ambiguous that every signatory nation interpreted them differently.`,
  options: [`unequivocal`, `contentious`, `perspicuous`, `nebulous`, `verbose`, `immutable`],
  correctAnswer: [`unequivocal`, `perspicuous`],
  explanation: `Both contrast with ambiguity: "unequivocal" and "perspicuous" mean clear.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v88`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The philosopher's later essays, while intellectually rigorous, were widely criticized for their __________ prose style that alienated general readers.`,
  options: [`abstruse`, `limpid`, `recondite`, `effulgent`, `pellucid`, `trenchant`],
  correctAnswer: [`abstruse`, `recondite`],
  explanation: `Both describe difficult, obscure prose that alienates general readers.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v89`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The CEO's apology was widely regarded as __________, offering contrition without acknowledging any specific wrongdoing.`,
  options: [`heartfelt`, `perfunctory`, `cursory`, `effusive`, `penitent`, `solemn`],
  correctAnswer: [`perfunctory`, `cursory`],
  explanation: `Surface contrition without specifics is perfunctory or cursory.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v90`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The landscape after the drought appeared __________, devoid of the lush vegetation that had defined the region for centuries.`,
  options: [`verdant`, `arid`, `bucolic`, `parched`, `sylvan`, `luxuriant`],
  correctAnswer: [`arid`, `parched`],
  explanation: `Both describe dry, vegetation-depleted conditions.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v91`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The documentary's tone was surprisingly __________, treating its grim subject matter with a lightness that many viewers found inappropriate.`,
  options: [`lugubrious`, `flippant`, `mordant`, `jocular`, `solemn`, `scathing`],
  correctAnswer: [`flippant`, `jocular`],
  explanation: `Both "flippant" and "jocular" convey inappropriate lightness.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v92`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `Far from being __________, the treaty's provisions were so ambiguous that every signatory nation interpreted them differently.`,
  options: [`unequivocal`, `contentious`, `perspicuous`, `nebulous`, `verbose`, `immutable`],
  correctAnswer: [`unequivocal`, `perspicuous`],
  explanation: `Both contrast with ambiguity: "unequivocal" and "perspicuous" mean clear.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v93`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The philosopher's later essays, while intellectually rigorous, were widely criticized for their __________ prose style that alienated general readers.`,
  options: [`abstruse`, `limpid`, `recondite`, `effulgent`, `pellucid`, `trenchant`],
  correctAnswer: [`abstruse`, `recondite`],
  explanation: `Both describe difficult, obscure prose that alienates general readers.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v94`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The CEO's apology was widely regarded as __________, offering contrition without acknowledging any specific wrongdoing.`,
  options: [`heartfelt`, `perfunctory`, `cursory`, `effusive`, `penitent`, `solemn`],
  correctAnswer: [`perfunctory`, `cursory`],
  explanation: `Surface contrition without specifics is perfunctory or cursory.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v95`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The landscape after the drought appeared __________, devoid of the lush vegetation that had defined the region for centuries.`,
  options: [`verdant`, `arid`, `bucolic`, `parched`, `sylvan`, `luxuriant`],
  correctAnswer: [`arid`, `parched`],
  explanation: `Both describe dry, vegetation-depleted conditions.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v96`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The documentary's tone was surprisingly __________, treating its grim subject matter with a lightness that many viewers found inappropriate.`,
  options: [`lugubrious`, `flippant`, `mordant`, `jocular`, `solemn`, `scathing`],
  correctAnswer: [`flippant`, `jocular`],
  explanation: `Both "flippant" and "jocular" convey inappropriate lightness.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v97`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `Far from being __________, the treaty's provisions were so ambiguous that every signatory nation interpreted them differently.`,
  options: [`unequivocal`, `contentious`, `perspicuous`, `nebulous`, `verbose`, `immutable`],
  correctAnswer: [`unequivocal`, `perspicuous`],
  explanation: `Both contrast with ambiguity: "unequivocal" and "perspicuous" mean clear.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v98`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The philosopher's later essays, while intellectually rigorous, were widely criticized for their __________ prose style that alienated general readers.`,
  options: [`abstruse`, `limpid`, `recondite`, `effulgent`, `pellucid`, `trenchant`],
  correctAnswer: [`abstruse`, `recondite`],
  explanation: `Both describe difficult, obscure prose that alienates general readers.`,
  difficulty: `medium`,
  tags: [`sentence-equivalence`],
},

{
  id: `v99`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The CEO's apology was widely regarded as __________, offering contrition without acknowledging any specific wrongdoing.`,
  options: [`heartfelt`, `perfunctory`, `cursory`, `effusive`, `penitent`, `solemn`],
  correctAnswer: [`perfunctory`, `cursory`],
  explanation: `Surface contrition without specifics is perfunctory or cursory.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
},

{
  id: `v100`,
  section: `verbal`,
  type: `sentence-equivalence`,
  prompt: `The landscape after the drought appeared __________, devoid of the lush vegetation that had defined the region for centuries.`,
  options: [`verdant`, `arid`, `bucolic`, `parched`, `sylvan`, `luxuriant`],
  correctAnswer: [`arid`, `parched`],
  explanation: `Both describe dry, vegetation-depleted conditions.`,
  difficulty: `hard`,
  tags: [`sentence-equivalence`],
}
];
