import { Question } from "../../types";

export const textCompletionQuestions: Question[] = [
{
  id: `v41`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Although critics initially dismissed the sculptor's minimalist works as merely __________, subsequent decades of scholarship have revealed a profound engagement with Zen philosophy that had been hiding in plain sight.`,
  options: [`derivative`, `vacuous`, `ostentatious`, `labyrinthine`, `pedantic`],
  correctAnswer: `vacuous`,
  explanation: `"Vacuous" captures the charge that works lacked substance—exactly what later scholarship refutes.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v42`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `The senator's speech was notable for its __________ quality: each anecdote seemed chosen not to illuminate an argument but simply to delay the audience's realization that no argument existed.`,
  options: [`turgid`, `laconic`, `dilatory`, `incisive`, `pellucid`],
  correctAnswer: `dilatory`,
  explanation: `"Dilatory" means intended to cause delay, matching anecdotes used to stall realization.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v43`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `The biographer's portrait of the novelist was so (i)__________ that even admirers conceded it exposed previously (ii)__________ flaws in the author's character.`,
  options: [`(i) hagiographic | (ii) celebrated`, `(i) unflinching | (ii) overlooked`, `(i) superficial | (ii) documented`, `(i) tendentious | (ii) imaginary`, `(i) effusive | (ii) exaggerated`],
  correctAnswer: `(i) unflinching | (ii) overlooked`,
  explanation: `An "unflinching" biography exposes hard truths; admirers conceding implies flaws were "overlooked."`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v44`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `The new management's strategy was __________: it promised sweeping innovation while quietly preserving every legacy system that had made the company profitable.`,
  options: [`audacious`, `Janus-faced`, `jejune`, `Sisyphean`, `lachrymose`],
  correctAnswer: `Janus-faced`,
  explanation: `"Janus-faced" means duplicitous—public promise versus private preservation of the status quo.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v45`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `The diplomat's remarks were deliberately __________, allowing each faction to interpret them as endorsement of its own position.`,
  options: [`trenchant`, `equivocal`, `prosaic`, `vitriolic`, `didactic`],
  correctAnswer: `equivocal`,
  explanation: `Ambiguous language lets opposing groups read in their preferred meaning.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v46`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Far from being a __________ account, the memoir candidly documented failures that most public figures prefer to omit.`,
  options: [`sanitized`, `penurious`, `soporific`, `iridescent`, `nascent`],
  correctAnswer: `sanitized`,
  explanation: `Candid failure contrasts with a cleaned-up, sanitized narrative.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v47`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `The committee's report was so __________ with jargon that legislators complained they could not extract a single actionable recommendation.`,
  options: [`replete`, `devoid`, `impartial`, `spartan`, `transient`],
  correctAnswer: `replete`,
  explanation: `"Replete with jargon" means filled with opaque terminology blocking clarity.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v48`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Her critique was not merely negative but __________, dismantling the theory's core assumptions with surgical precision.`,
  options: [`perfunctory`, `devastating`, `oblique`, `magnanimous`, `desultory`],
  correctAnswer: `devastating`,
  explanation: `Surgical dismantling of core assumptions implies a devastating critique.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v49`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `The archaeologist remained __________ about the artifact's origin until carbon dating confirmed her hypothesis.`,
  options: [`sanguine`, `categorically`, `circumspect`, `effusive`, `truculent`],
  correctAnswer: `circumspect`,
  explanation: `Waiting for confirmation before claiming origin shows cautious, circumspect judgment.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v50`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `The poet's early work was __________, borrowing themes freely without yet developing a distinctive voice.`,
  options: [`iconoclastic`, `eclectic`, `hermetic`, `austere`, `synthetic`],
  correctAnswer: `eclectic`,
  explanation: `Borrowing widely without a distinct voice suggests eclectic rather than unified style.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v51`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Although critics initially dismissed the sculptor's minimalist works as merely __________, subsequent decades of scholarship have revealed a profound engagement with Zen philosophy that had been hiding in plain sight.`,
  options: [`derivative`, `vacuous`, `ostentatious`, `labyrinthine`, `pedantic`],
  correctAnswer: `vacuous`,
  explanation: `"Vacuous" captures the charge that works lacked substance—exactly what later scholarship refutes.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v52`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the senator's speech was notable for its __________ quality: each anecdote seemed chosen not to illuminate an argument but simply to delay the audience's realization that no argument existed.`,
  options: [`turgid`, `laconic`, `dilatory`, `incisive`, `pellucid`],
  correctAnswer: `dilatory`,
  explanation: `"Dilatory" means intended to cause delay, matching anecdotes used to stall realization.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v53`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the biographer's portrait of the novelist was so (i)__________ that even admirers conceded it exposed previously (ii)__________ flaws in the author's character.`,
  options: [`(i) hagiographic | (ii) celebrated`, `(i) unflinching | (ii) overlooked`, `(i) superficial | (ii) documented`, `(i) tendentious | (ii) imaginary`, `(i) effusive | (ii) exaggerated`],
  correctAnswer: `(i) unflinching | (ii) overlooked`,
  explanation: `An "unflinching" biography exposes hard truths; admirers conceding implies flaws were "overlooked."`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v54`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the new management's strategy was __________: it promised sweeping innovation while quietly preserving every legacy system that had made the company profitable.`,
  options: [`audacious`, `Janus-faced`, `jejune`, `Sisyphean`, `lachrymose`],
  correctAnswer: `Janus-faced`,
  explanation: `"Janus-faced" means duplicitous—public promise versus private preservation of the status quo.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v55`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the diplomat's remarks were deliberately __________, allowing each faction to interpret them as endorsement of its own position.`,
  options: [`trenchant`, `equivocal`, `prosaic`, `vitriolic`, `didactic`],
  correctAnswer: `equivocal`,
  explanation: `Ambiguous language lets opposing groups read in their preferred meaning.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v56`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Far from being a __________ account, the memoir candidly documented failures that most public figures prefer to omit.`,
  options: [`sanitized`, `penurious`, `soporific`, `iridescent`, `nascent`],
  correctAnswer: `sanitized`,
  explanation: `Candid failure contrasts with a cleaned-up, sanitized narrative.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v57`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the committee's report was so __________ with jargon that legislators complained they could not extract a single actionable recommendation.`,
  options: [`replete`, `devoid`, `impartial`, `spartan`, `transient`],
  correctAnswer: `replete`,
  explanation: `"Replete with jargon" means filled with opaque terminology blocking clarity.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v58`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Her critique was not merely negative but __________, dismantling the theory's core assumptions with surgical precision.`,
  options: [`perfunctory`, `devastating`, `oblique`, `magnanimous`, `desultory`],
  correctAnswer: `devastating`,
  explanation: `Surgical dismantling of core assumptions implies a devastating critique.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v59`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the archaeologist remained __________ about the artifact's origin until carbon dating confirmed her hypothesis.`,
  options: [`sanguine`, `categorically`, `circumspect`, `effusive`, `truculent`],
  correctAnswer: `circumspect`,
  explanation: `Waiting for confirmation before claiming origin shows cautious, circumspect judgment.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v60`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the poet's early work was __________, borrowing themes freely without yet developing a distinctive voice.`,
  options: [`iconoclastic`, `eclectic`, `hermetic`, `austere`, `synthetic`],
  correctAnswer: `eclectic`,
  explanation: `Borrowing widely without a distinct voice suggests eclectic rather than unified style.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v61`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Although critics initially dismissed the sculptor's minimalist works as merely __________, subsequent decades of scholarship have revealed a profound engagement with Zen philosophy that had been hiding in plain sight.`,
  options: [`derivative`, `vacuous`, `ostentatious`, `labyrinthine`, `pedantic`],
  correctAnswer: `vacuous`,
  explanation: `"Vacuous" captures the charge that works lacked substance—exactly what later scholarship refutes.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v62`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the senator's speech was notable for its __________ quality: each anecdote seemed chosen not to illuminate an argument but simply to delay the audience's realization that no argument existed.`,
  options: [`turgid`, `laconic`, `dilatory`, `incisive`, `pellucid`],
  correctAnswer: `dilatory`,
  explanation: `"Dilatory" means intended to cause delay, matching anecdotes used to stall realization.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v63`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the biographer's portrait of the novelist was so (i)__________ that even admirers conceded it exposed previously (ii)__________ flaws in the author's character.`,
  options: [`(i) hagiographic | (ii) celebrated`, `(i) unflinching | (ii) overlooked`, `(i) superficial | (ii) documented`, `(i) tendentious | (ii) imaginary`, `(i) effusive | (ii) exaggerated`],
  correctAnswer: `(i) unflinching | (ii) overlooked`,
  explanation: `An "unflinching" biography exposes hard truths; admirers conceding implies flaws were "overlooked."`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v64`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the new management's strategy was __________: it promised sweeping innovation while quietly preserving every legacy system that had made the company profitable.`,
  options: [`audacious`, `Janus-faced`, `jejune`, `Sisyphean`, `lachrymose`],
  correctAnswer: `Janus-faced`,
  explanation: `"Janus-faced" means duplicitous—public promise versus private preservation of the status quo.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v65`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the diplomat's remarks were deliberately __________, allowing each faction to interpret them as endorsement of its own position.`,
  options: [`trenchant`, `equivocal`, `prosaic`, `vitriolic`, `didactic`],
  correctAnswer: `equivocal`,
  explanation: `Ambiguous language lets opposing groups read in their preferred meaning.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v66`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Far from being a __________ account, the memoir candidly documented failures that most public figures prefer to omit.`,
  options: [`sanitized`, `penurious`, `soporific`, `iridescent`, `nascent`],
  correctAnswer: `sanitized`,
  explanation: `Candid failure contrasts with a cleaned-up, sanitized narrative.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v67`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the committee's report was so __________ with jargon that legislators complained they could not extract a single actionable recommendation.`,
  options: [`replete`, `devoid`, `impartial`, `spartan`, `transient`],
  correctAnswer: `replete`,
  explanation: `"Replete with jargon" means filled with opaque terminology blocking clarity.`,
  difficulty: `hard`,
  tags: [`text-completion`],
},

{
  id: `v68`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Her critique was not merely negative but __________, dismantling the theory's core assumptions with surgical precision.`,
  options: [`perfunctory`, `devastating`, `oblique`, `magnanimous`, `desultory`],
  correctAnswer: `devastating`,
  explanation: `Surgical dismantling of core assumptions implies a devastating critique.`,
  difficulty: `easy`,
  tags: [`text-completion`],
},

{
  id: `v69`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the archaeologist remained __________ about the artifact's origin until carbon dating confirmed her hypothesis.`,
  options: [`sanguine`, `categorically`, `circumspect`, `effusive`, `truculent`],
  correctAnswer: `circumspect`,
  explanation: `Waiting for confirmation before claiming origin shows cautious, circumspect judgment.`,
  difficulty: `medium`,
  tags: [`text-completion`],
},

{
  id: `v70`,
  section: `verbal`,
  type: `text-completion`,
  prompt: `Critics noted the poet's early work was __________, borrowing themes freely without yet developing a distinctive voice.`,
  options: [`iconoclastic`, `eclectic`, `hermetic`, `austere`, `synthetic`],
  correctAnswer: `eclectic`,
  explanation: `Borrowing widely without a distinct voice suggests eclectic rather than unified style.`,
  difficulty: `hard`,
  tags: [`text-completion`],
}
];
