import { Question } from "../../types";

export const algebraQuestions: Question[] = [
{
  id: `q26`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 3x − 7 = 5x + 1, what is x²?`,
  options: [`4`, `8`, `16`, `−4`, `64`],
  correctAnswer: `16`,
  explanation: `3x − 7 = 5x + 1 → −2x = 8 → x = −4. x² = 16.`,
  difficulty: `medium`,
  tags: [`algebra`],
},

{
  id: `q27`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `The sum of three consecutive even integers is 78. What is the largest?`,
  options: [`24`, `26`, `28`, `30`, `32`],
  correctAnswer: `28`,
  explanation: `n + (n+2) + (n+4) = 78 → n = 24. Largest = 28.`,
  difficulty: `easy`,
  tags: [`algebra`],
},

{
  id: `q28`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If f(x) = x² − 3x + 2, what is f(5) − f(2)?`,
  options: [`12`, `10`, `14`, `16`, `8`],
  correctAnswer: `12`,
  explanation: `f(5) = 12, f(2) = 0. Difference = 12.`,
  difficulty: `medium`,
  tags: [`algebra`],
},

{
  id: `q29`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 5x + 6 = 11x, what is x²?`,
  options: [`1`, `2`, `0`, `5`, `10`],
  correctAnswer: `1`,
  explanation: `5x + 6 = 11x → 6 = 6x → x = 1. x² = 1.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q30`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 6x + 7 = 13x, what is x²?`,
  options: [`1`, `2`, `0`, `5`, `10`],
  correctAnswer: `1`,
  explanation: `6x + 7 = 13x → 7 = 7x → x = 1. x² = 1.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q31`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 2x + 8 = 10x, what is x²?`,
  options: [`36`, `37`, `35`, `40`, `45`],
  correctAnswer: `36`,
  explanation: `2x + 8 = 10x → 8 = 8x → x = 6. x² = 36.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q32`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 3x + 9 = 12x, what is x²?`,
  options: [`36`, `37`, `35`, `40`, `45`],
  correctAnswer: `36`,
  explanation: `3x + 9 = 12x → 9 = 9x → x = 6. x² = 36.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q33`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 4x + 3 = 7x, what is x²?`,
  options: [`1`, `2`, `0`, `5`, `10`],
  correctAnswer: `1`,
  explanation: `4x + 3 = 7x → 3 = 3x → x = -1. x² = 1.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q34`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 5x + 4 = 9x, what is x²?`,
  options: [`1`, `2`, `0`, `5`, `10`],
  correctAnswer: `1`,
  explanation: `5x + 4 = 9x → 4 = 4x → x = -1. x² = 1.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q35`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 6x + 5 = 11x, what is x²?`,
  options: [`1`, `2`, `0`, `5`, `10`],
  correctAnswer: `1`,
  explanation: `6x + 5 = 11x → 5 = 5x → x = -1. x² = 1.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q36`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 2x + 6 = 8x, what is x²?`,
  options: [`16`, `17`, `15`, `20`, `25`],
  correctAnswer: `16`,
  explanation: `2x + 6 = 8x → 6 = 6x → x = 4. x² = 16.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q37`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 3x + 7 = 10x, what is x²?`,
  options: [`16`, `17`, `15`, `20`, `25`],
  correctAnswer: `16`,
  explanation: `3x + 7 = 10x → 7 = 7x → x = 4. x² = 16.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q38`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 4x + 8 = 12x, what is x²?`,
  options: [`16`, `17`, `15`, `20`, `25`],
  correctAnswer: `16`,
  explanation: `4x + 8 = 12x → 8 = 8x → x = 4. x² = 16.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q39`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 5x + 9 = 14x, what is x²?`,
  options: [`16`, `17`, `15`, `20`, `25`],
  correctAnswer: `16`,
  explanation: `5x + 9 = 14x → 9 = 9x → x = 4. x² = 16.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q40`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 6x + 3 = 9x, what is x²?`,
  options: [`9`, `10`, `8`, `13`, `18`],
  correctAnswer: `9`,
  explanation: `6x + 3 = 9x → 3 = 3x → x = -3. x² = 9.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q41`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 2x + 4 = 6x, what is x²?`,
  options: [`4`, `5`, `3`, `8`, `13`],
  correctAnswer: `4`,
  explanation: `2x + 4 = 6x → 4 = 4x → x = 2. x² = 4.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q42`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 3x + 5 = 8x, what is x²?`,
  options: [`4`, `5`, `3`, `8`, `13`],
  correctAnswer: `4`,
  explanation: `3x + 5 = 8x → 5 = 5x → x = 2. x² = 4.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q43`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 4x + 6 = 10x, what is x²?`,
  options: [`4`, `5`, `3`, `8`, `13`],
  correctAnswer: `4`,
  explanation: `4x + 6 = 10x → 6 = 6x → x = 2. x² = 4.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q44`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 5x + 7 = 12x, what is x²?`,
  options: [`4`, `5`, `3`, `8`, `13`],
  correctAnswer: `4`,
  explanation: `5x + 7 = 12x → 7 = 7x → x = 2. x² = 4.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q45`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 6x + 8 = 14x, what is x²?`,
  options: [`4`, `5`, `3`, `8`, `13`],
  correctAnswer: `4`,
  explanation: `6x + 8 = 14x → 8 = 8x → x = 2. x² = 4.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q46`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 2x + 9 = 11x, what is x²?`,
  options: [`49`, `50`, `48`, `53`, `58`],
  correctAnswer: `49`,
  explanation: `2x + 9 = 11x → 9 = 9x → x = 7. x² = 49.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q47`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 3x + 3 = 6x, what is x²?`,
  options: [`0`, `1`, `-1`, `4`, `9`],
  correctAnswer: `0`,
  explanation: `3x + 3 = 6x → 3 = 3x → x = 0. x² = 0.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q48`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 4x + 4 = 8x, what is x²?`,
  options: [`0`, `1`, `-1`, `4`, `9`],
  correctAnswer: `0`,
  explanation: `4x + 4 = 8x → 4 = 4x → x = 0. x² = 0.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q49`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 5x + 5 = 10x, what is x²?`,
  options: [`0`, `1`, `-1`, `4`, `9`],
  correctAnswer: `0`,
  explanation: `5x + 5 = 10x → 5 = 5x → x = 0. x² = 0.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
},

{
  id: `q50`,
  section: `quantitative`,
  type: `algebra`,
  prompt: `If 6x + 6 = 12x, what is x²?`,
  options: [`0`, `1`, `-1`, `4`, `9`],
  correctAnswer: `0`,
  explanation: `6x + 6 = 12x → 6 = 6x → x = 0. x² = 0.`,
  difficulty: `medium`,
  tags: [`algebra`, `linear`],
}
];
