import { Question } from "../../types";

export const dataanalysisQuestions: Question[] = [
{
  id: `q76`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `Mean of five numbers is 18. Four are 12, 15, 21, 24. Fifth number?`,
  options: [`16`, `17`, `18`, `19`, `20`],
  correctAnswer: `18`,
  explanation: `Sum = 90. Known sum = 72. Fifth = 18.`,
  difficulty: `easy`,
  tags: [`data-analysis`, `mean`],
},

{
  id: `q77`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `Class of 30: boys to girls ratio 2:3. How many girls?`,
  options: [`12`, `15`, `16`, `18`, `20`],
  correctAnswer: `18`,
  explanation: `Girls = (3/5) × 30 = 18.`,
  difficulty: `easy`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q78`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 30 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`18`, `16`, `20`, `22`, `14`],
  correctAnswer: `18`,
  explanation: `Seniors = (3/5) × 30 = 18.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q79`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 35 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`21`, `19`, `23`, `25`, `17`],
  correctAnswer: `21`,
  explanation: `Seniors = (3/5) × 35 = 21.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q80`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 40 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`24`, `22`, `26`, `28`, `20`],
  correctAnswer: `24`,
  explanation: `Seniors = (3/5) × 40 = 24.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q81`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 45 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`27`, `25`, `29`, `31`, `23`],
  correctAnswer: `27`,
  explanation: `Seniors = (3/5) × 45 = 27.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q82`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 50 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`30`, `28`, `32`, `34`, `26`],
  correctAnswer: `30`,
  explanation: `Seniors = (3/5) × 50 = 30.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q83`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 55 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`33`, `31`, `35`, `37`, `29`],
  correctAnswer: `33`,
  explanation: `Seniors = (3/5) × 55 = 33.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q84`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 60 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`36`, `34`, `38`, `40`, `32`],
  correctAnswer: `36`,
  explanation: `Seniors = (3/5) × 60 = 36.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q85`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 65 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`39`, `37`, `41`, `43`, `35`],
  correctAnswer: `39`,
  explanation: `Seniors = (3/5) × 65 = 39.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q86`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 20 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`12`, `10`, `14`, `16`, `8`],
  correctAnswer: `12`,
  explanation: `Seniors = (3/5) × 20 = 12.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q87`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 25 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`15`, `13`, `17`, `19`, `11`],
  correctAnswer: `15`,
  explanation: `Seniors = (3/5) × 25 = 15.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q88`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 30 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`18`, `16`, `20`, `22`, `14`],
  correctAnswer: `18`,
  explanation: `Seniors = (3/5) × 30 = 18.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q89`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 35 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`21`, `19`, `23`, `25`, `17`],
  correctAnswer: `21`,
  explanation: `Seniors = (3/5) × 35 = 21.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q90`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 40 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`24`, `22`, `26`, `28`, `20`],
  correctAnswer: `24`,
  explanation: `Seniors = (3/5) × 40 = 24.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q91`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 45 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`27`, `25`, `29`, `31`, `23`],
  correctAnswer: `27`,
  explanation: `Seniors = (3/5) × 45 = 27.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q92`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 50 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`30`, `28`, `32`, `34`, `26`],
  correctAnswer: `30`,
  explanation: `Seniors = (3/5) × 50 = 30.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q93`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 55 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`33`, `31`, `35`, `37`, `29`],
  correctAnswer: `33`,
  explanation: `Seniors = (3/5) × 55 = 33.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q94`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 60 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`36`, `34`, `38`, `40`, `32`],
  correctAnswer: `36`,
  explanation: `Seniors = (3/5) × 60 = 36.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q95`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 65 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`39`, `37`, `41`, `43`, `35`],
  correctAnswer: `39`,
  explanation: `Seniors = (3/5) × 65 = 39.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q96`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 20 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`12`, `10`, `14`, `16`, `8`],
  correctAnswer: `12`,
  explanation: `Seniors = (3/5) × 20 = 12.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q97`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 25 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`15`, `13`, `17`, `19`, `11`],
  correctAnswer: `15`,
  explanation: `Seniors = (3/5) × 25 = 15.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q98`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 30 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`18`, `16`, `20`, `22`, `14`],
  correctAnswer: `18`,
  explanation: `Seniors = (3/5) × 30 = 18.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q99`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 35 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`21`, `19`, `23`, `25`, `17`],
  correctAnswer: `21`,
  explanation: `Seniors = (3/5) × 35 = 21.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
},

{
  id: `q100`,
  section: `quantitative`,
  type: `data-analysis`,
  prompt: `In a group of 40 students, the ratio of juniors to seniors is 2:3. How many seniors?`,
  options: [`24`, `22`, `26`, `28`, `20`],
  correctAnswer: `24`,
  explanation: `Seniors = (3/5) × 40 = 24.`,
  difficulty: `medium`,
  tags: [`data-analysis`, `ratio`],
}
];
