import { Question } from "../../types";

export const geometryQuestions: Question[] = [
{
  id: `q51`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 9 and 12. Hypotenuse length?`,
  options: [`13`, `14`, `15`, `16`, `17`],
  correctAnswer: `15`,
  explanation: `c² = 81 + 144 = 225. c = 15.`,
  difficulty: `easy`,
  tags: [`geometry`, `pythagorean`],
},

{
  id: `q52`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A circle has area 49π. Circumference?`,
  options: [`7π`, `14π`, `49π`, `28π`, `21π`],
  correctAnswer: `14π`,
  explanation: `πr² = 49π → r = 7. C = 14π.`,
  difficulty: `easy`,
  tags: [`geometry`, `circle`],
},

{
  id: `q53`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 7 and 8. Which is closest to the hypotenuse?`,
  options: [`11`, `12`, `10`, `13`, `14`],
  correctAnswer: `11`,
  explanation: `c = √(7² + 8²) ≈ 11.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q54`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 8 and 9. Which is closest to the hypotenuse?`,
  options: [`12`, `13`, `11`, `14`, `15`],
  correctAnswer: `12`,
  explanation: `c = √(8² + 9²) ≈ 12.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q55`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 9 and 10. Which is closest to the hypotenuse?`,
  options: [`13`, `14`, `12`, `15`, `16`],
  correctAnswer: `13`,
  explanation: `c = √(9² + 10²) ≈ 13.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q56`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 10 and 11. Which is closest to the hypotenuse?`,
  options: [`15`, `16`, `14`, `17`, `18`],
  correctAnswer: `15`,
  explanation: `c = √(10² + 11²) ≈ 15.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q57`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 11 and 12. Which is closest to the hypotenuse?`,
  options: [`16`, `17`, `15`, `18`, `19`],
  correctAnswer: `16`,
  explanation: `c = √(11² + 12²) ≈ 16.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q58`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 12 and 13. Which is closest to the hypotenuse?`,
  options: [`18`, `19`, `17`, `20`, `21`],
  correctAnswer: `18`,
  explanation: `c = √(12² + 13²) ≈ 18.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q59`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 5 and 6. Which is closest to the hypotenuse?`,
  options: [`8`, `9`, `7`, `10`, `11`],
  correctAnswer: `8`,
  explanation: `c = √(5² + 6²) ≈ 8.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q60`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 6 and 7. Which is closest to the hypotenuse?`,
  options: [`9`, `10`, `8`, `11`, `12`],
  correctAnswer: `9`,
  explanation: `c = √(6² + 7²) ≈ 9.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q61`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 7 and 8. Which is closest to the hypotenuse?`,
  options: [`11`, `12`, `10`, `13`, `14`],
  correctAnswer: `11`,
  explanation: `c = √(7² + 8²) ≈ 11.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q62`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 8 and 9. Which is closest to the hypotenuse?`,
  options: [`12`, `13`, `11`, `14`, `15`],
  correctAnswer: `12`,
  explanation: `c = √(8² + 9²) ≈ 12.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q63`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 9 and 10. Which is closest to the hypotenuse?`,
  options: [`13`, `14`, `12`, `15`, `16`],
  correctAnswer: `13`,
  explanation: `c = √(9² + 10²) ≈ 13.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q64`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 10 and 11. Which is closest to the hypotenuse?`,
  options: [`15`, `16`, `14`, `17`, `18`],
  correctAnswer: `15`,
  explanation: `c = √(10² + 11²) ≈ 15.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q65`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 11 and 12. Which is closest to the hypotenuse?`,
  options: [`16`, `17`, `15`, `18`, `19`],
  correctAnswer: `16`,
  explanation: `c = √(11² + 12²) ≈ 16.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q66`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 12 and 13. Which is closest to the hypotenuse?`,
  options: [`18`, `19`, `17`, `20`, `21`],
  correctAnswer: `18`,
  explanation: `c = √(12² + 13²) ≈ 18.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q67`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 5 and 6. Which is closest to the hypotenuse?`,
  options: [`8`, `9`, `7`, `10`, `11`],
  correctAnswer: `8`,
  explanation: `c = √(5² + 6²) ≈ 8.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q68`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 6 and 7. Which is closest to the hypotenuse?`,
  options: [`9`, `10`, `8`, `11`, `12`],
  correctAnswer: `9`,
  explanation: `c = √(6² + 7²) ≈ 9.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q69`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 7 and 8. Which is closest to the hypotenuse?`,
  options: [`11`, `12`, `10`, `13`, `14`],
  correctAnswer: `11`,
  explanation: `c = √(7² + 8²) ≈ 11.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q70`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 8 and 9. Which is closest to the hypotenuse?`,
  options: [`12`, `13`, `11`, `14`, `15`],
  correctAnswer: `12`,
  explanation: `c = √(8² + 9²) ≈ 12.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q71`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 9 and 10. Which is closest to the hypotenuse?`,
  options: [`13`, `14`, `12`, `15`, `16`],
  correctAnswer: `13`,
  explanation: `c = √(9² + 10²) ≈ 13.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q72`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 10 and 11. Which is closest to the hypotenuse?`,
  options: [`15`, `16`, `14`, `17`, `18`],
  correctAnswer: `15`,
  explanation: `c = √(10² + 11²) ≈ 15.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q73`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 11 and 12. Which is closest to the hypotenuse?`,
  options: [`16`, `17`, `15`, `18`, `19`],
  correctAnswer: `16`,
  explanation: `c = √(11² + 12²) ≈ 16.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q74`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 12 and 13. Which is closest to the hypotenuse?`,
  options: [`18`, `19`, `17`, `20`, `21`],
  correctAnswer: `18`,
  explanation: `c = √(12² + 13²) ≈ 18.`,
  difficulty: `medium`,
  tags: [`geometry`],
},

{
  id: `q75`,
  section: `quantitative`,
  type: `geometry`,
  prompt: `A right triangle has legs 5 and 6. Which is closest to the hypotenuse?`,
  options: [`8`, `9`, `7`, `10`, `11`],
  correctAnswer: `8`,
  explanation: `c = √(5² + 6²) ≈ 8.`,
  difficulty: `medium`,
  tags: [`geometry`],
}
];
